
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label_address;
	private global::Gtk.Entry entry_address;
	private global::Gtk.Button button_address_ok;
	private global::Gtk.Label GtkLabel1;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.Table table1;
	private global::Gtk.ComboBox combobox_font_static_text;
	private global::Gtk.ComboBox combobox_font_time;
	private global::Gtk.ComboBox combobox3;
	private global::Gtk.RadioButton radiobutton_all;
	private global::Gtk.RadioButton radiobutton_static_text;
	private global::Gtk.RadioButton radiobutton_time;
	private global::Gtk.RadioButton radiobutton_void;
	private global::Gtk.RadioButton radiobutton_winamp;
	private global::Gtk.Label GtkLabel7;
	private global::Gtk.VBox vbox98;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Frame frame3;
	private global::Gtk.VBox vbox99;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.Entry entry_static_text;
	private global::Gtk.CheckButton checkbutton_static_text_auto_scroll;
	private global::Gtk.HScale hscale_x_pos;
	private global::Gtk.Label GtkLabel8;
	private global::Gtk.VScale vscale_y_pos;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.HScale hscale_shift_speed;
	private global::Gtk.Label GtkLabel9;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.BorderWidth = ((uint)(9));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label_address = new global::Gtk.Label ();
		this.label_address.Name = "label_address";
		this.label_address.LabelProp = global::Mono.Unix.Catalog.GetString ("Ledmatrix Adresse");
		this.hbox2.Add (this.label_address);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label_address]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry_address = new global::Gtk.Entry ();
		this.entry_address.CanFocus = true;
		this.entry_address.Name = "entry_address";
		this.entry_address.IsEditable = true;
		this.entry_address.InvisibleChar = '•';
		this.hbox2.Add (this.entry_address);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry_address]));
		w2.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button_address_ok = new global::Gtk.Button ();
		this.button_address_ok.CanFocus = true;
		this.button_address_ok.Name = "button_address_ok";
		this.button_address_ok.UseUnderline = true;
		this.button_address_ok.Label = global::Mono.Unix.Catalog.GetString ("OK");
		this.hbox2.Add (this.button_address_ok);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button_address_ok]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.GtkAlignment.Add (this.hbox2);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Einstellungen</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel1;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame2.BorderWidth = ((uint)(6));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.combobox_font_static_text = global::Gtk.ComboBox.NewText ();
		this.combobox_font_static_text.AppendText (global::Mono.Unix.Catalog.GetString ("Font8x12"));
		this.combobox_font_static_text.AppendText (global::Mono.Unix.Catalog.GetString ("Font8x8"));
		this.combobox_font_static_text.Name = "combobox_font_static_text";
		this.combobox_font_static_text.Active = 0;
		this.table1.Add (this.combobox_font_static_text);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox_font_static_text]));
		w7.TopAttach = ((uint)(3));
		w7.BottomAttach = ((uint)(4));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combobox_font_time = global::Gtk.ComboBox.NewText ();
		this.combobox_font_time.AppendText (global::Mono.Unix.Catalog.GetString ("Font8x12"));
		this.combobox_font_time.AppendText (global::Mono.Unix.Catalog.GetString ("Font8x8"));
		this.combobox_font_time.Name = "combobox_font_time";
		this.combobox_font_time.Active = 0;
		this.table1.Add (this.combobox_font_time);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox_font_time]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combobox3 = global::Gtk.ComboBox.NewText ();
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Font8x12"));
		this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Font8x8"));
		this.combobox3.Name = "combobox3";
		this.combobox3.Active = 0;
		this.table1.Add (this.combobox3);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox3]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobutton_all = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Alles an"));
		this.radiobutton_all.CanFocus = true;
		this.radiobutton_all.Name = "radiobutton_all";
		this.radiobutton_all.DrawIndicator = true;
		this.radiobutton_all.UseUnderline = true;
		this.radiobutton_all.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.table1.Add (this.radiobutton_all);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobutton_all]));
		w10.TopAttach = ((uint)(4));
		w10.BottomAttach = ((uint)(5));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobutton_static_text = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Statischer Text"));
		this.radiobutton_static_text.CanFocus = true;
		this.radiobutton_static_text.Name = "radiobutton_static_text";
		this.radiobutton_static_text.DrawIndicator = true;
		this.radiobutton_static_text.UseUnderline = true;
		this.radiobutton_static_text.Group = this.radiobutton_all.Group;
		this.table1.Add (this.radiobutton_static_text);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobutton_static_text]));
		w11.TopAttach = ((uint)(3));
		w11.BottomAttach = ((uint)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobutton_time = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Uhrzeit"));
		this.radiobutton_time.CanFocus = true;
		this.radiobutton_time.Name = "radiobutton_time";
		this.radiobutton_time.DrawIndicator = true;
		this.radiobutton_time.UseUnderline = true;
		this.radiobutton_time.Group = this.radiobutton_all.Group;
		this.table1.Add (this.radiobutton_time);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobutton_time]));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobutton_void = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Leer"));
		this.radiobutton_void.CanFocus = true;
		this.radiobutton_void.Name = "radiobutton_void";
		this.radiobutton_void.DrawIndicator = true;
		this.radiobutton_void.UseUnderline = true;
		this.radiobutton_void.Group = this.radiobutton_all.Group;
		this.table1.Add (this.radiobutton_void);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobutton_void]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.radiobutton_winamp = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Winamp"));
		this.radiobutton_winamp.CanFocus = true;
		this.radiobutton_winamp.Name = "radiobutton_winamp";
		this.radiobutton_winamp.DrawIndicator = true;
		this.radiobutton_winamp.UseUnderline = true;
		this.radiobutton_winamp.Group = this.radiobutton_all.Group;
		this.table1.Add (this.radiobutton_winamp);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.radiobutton_winamp]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment1.Add (this.table1);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Anzeige</b>");
		this.GtkLabel7.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel7;
		this.vbox1.Add (this.frame2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox98 = new global::Gtk.VBox ();
		this.vbox98.Name = "vbox98";
		this.vbox98.Spacing = 6;
		// Container child vbox98.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.WidthRequest = 367;
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame3.BorderWidth = ((uint)(6));
		// Container child frame3.Gtk.Container+ContainerChild
		this.vbox99 = new global::Gtk.VBox ();
		this.vbox99.Name = "vbox99";
		this.vbox99.Spacing = 6;
		// Container child vbox99.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.entry_static_text = new global::Gtk.Entry ();
		this.entry_static_text.CanFocus = true;
		this.entry_static_text.Name = "entry_static_text";
		this.entry_static_text.IsEditable = true;
		this.entry_static_text.InvisibleChar = '•';
		this.GtkAlignment2.Add (this.entry_static_text);
		this.hbox3.Add (this.GtkAlignment2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkAlignment2]));
		w19.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.checkbutton_static_text_auto_scroll = new global::Gtk.CheckButton ();
		this.checkbutton_static_text_auto_scroll.CanFocus = true;
		this.checkbutton_static_text_auto_scroll.Name = "checkbutton_static_text_auto_scroll";
		this.checkbutton_static_text_auto_scroll.Label = global::Mono.Unix.Catalog.GetString ("Auto Scroll");
		this.checkbutton_static_text_auto_scroll.DrawIndicator = true;
		this.checkbutton_static_text_auto_scroll.UseUnderline = true;
		this.hbox3.Add (this.checkbutton_static_text_auto_scroll);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.checkbutton_static_text_auto_scroll]));
		w20.Position = 1;
		this.vbox99.Add (this.hbox3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox99 [this.hbox3]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox99.Gtk.Box+BoxChild
		this.hscale_x_pos = new global::Gtk.HScale (null);
		this.hscale_x_pos.CanFocus = true;
		this.hscale_x_pos.Name = "hscale_x_pos";
		this.hscale_x_pos.Adjustment.Upper = 100;
		this.hscale_x_pos.Adjustment.PageIncrement = 1;
		this.hscale_x_pos.Adjustment.StepIncrement = 1;
		this.hscale_x_pos.DrawValue = true;
		this.hscale_x_pos.Digits = 0;
		this.hscale_x_pos.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox99.Add (this.hscale_x_pos);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox99 [this.hscale_x_pos]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.frame3.Add (this.vbox99);
		this.GtkLabel8 = new global::Gtk.Label ();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Statischer Text</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel8;
		this.hbox1.Add (this.frame3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame3]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vscale_y_pos = new global::Gtk.VScale (null);
		this.vscale_y_pos.CanFocus = true;
		this.vscale_y_pos.Name = "vscale_y_pos";
		this.vscale_y_pos.Adjustment.Lower = -5;
		this.vscale_y_pos.Adjustment.Upper = 5;
		this.vscale_y_pos.Adjustment.PageIncrement = 1;
		this.vscale_y_pos.Adjustment.StepIncrement = 1;
		this.vscale_y_pos.DrawValue = true;
		this.vscale_y_pos.Digits = 0;
		this.vscale_y_pos.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox1.Add (this.vscale_y_pos);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vscale_y_pos]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox98.Add (this.hbox1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox98 [this.hbox1]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox98.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.hscale_shift_speed = new global::Gtk.HScale (null);
		this.hscale_shift_speed.CanFocus = true;
		this.hscale_shift_speed.Name = "hscale_shift_speed";
		this.hscale_shift_speed.Adjustment.Upper = 100;
		this.hscale_shift_speed.Adjustment.PageIncrement = 1;
		this.hscale_shift_speed.Adjustment.StepIncrement = 1;
		this.hscale_shift_speed.DrawValue = true;
		this.hscale_shift_speed.Digits = 0;
		this.hscale_shift_speed.ValuePos = ((global::Gtk.PositionType)(2));
		this.GtkAlignment3.Add (this.hscale_shift_speed);
		this.frame4.Add (this.GtkAlignment3);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Scroll Geschwindigkeit</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel9;
		this.vbox3.Add (this.frame4);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame4]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox98.Add (this.vbox3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox98 [this.vbox3]));
		w30.Position = 1;
		this.vbox1.Add (this.vbox98);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox98]));
		w31.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 414;
		this.DefaultHeight = 600;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.entry_address.Activated += new global::System.EventHandler (this.on_entry_address_activated);
		this.button_address_ok.Clicked += new global::System.EventHandler (this.on_entry_address_activated);
		this.radiobutton_winamp.Toggled += new global::System.EventHandler (this.radiobutton_winamp_toggled);
		this.radiobutton_void.Toggled += new global::System.EventHandler (this.radiobutton_void_toggled);
		this.radiobutton_time.Toggled += new global::System.EventHandler (this.radiobutton_time_toggled);
		this.radiobutton_static_text.Toggled += new global::System.EventHandler (this.radiobutton_static_text_toggled);
		this.radiobutton_all.Toggled += new global::System.EventHandler (this.on_radiobutton_all_toggled);
		this.combobox_font_time.Changed += new global::System.EventHandler (this.on_combobox_font_time_changed);
		this.combobox_font_static_text.Changed += new global::System.EventHandler (this.on_combobox_font_static_text_changed);
		this.entry_static_text.Changed += new global::System.EventHandler (this.on_entry_static_text_changed);
		this.checkbutton_static_text_auto_scroll.Toggled += new global::System.EventHandler (this.on_togglebutton_static_text_auto_scroll_toggled);
		this.hscale_x_pos.ValueChanged += new global::System.EventHandler (this.on_hscale_x_pos_changed);
		this.vscale_y_pos.ValueChanged += new global::System.EventHandler (this.on_vscale_y_pos_changed);
		this.hscale_shift_speed.ValueChanged += new global::System.EventHandler (this.hscale_shift_speed_changed);
	}
}
