
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Table table2;
	private global::Gtk.Button button_address_ok;
	private global::Gtk.CheckButton checkbutton_loop;
	private global::Gtk.Entry entry_address;
	private global::Gtk.Entry entry_mpd;
	private global::Gtk.Entry entry_winamp_address;
	private global::Gtk.Entry entry_winamp_pass;
	private global::Gtk.Entry entry_winamp_port;
	private global::Gtk.HScale hscale_shift_speed;
	private global::Gtk.Label label_address;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label GtkLabel2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeview2;
	private global::Gtk.Label label1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.BorderWidth = ((uint)(9));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(4)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		this.table2.BorderWidth = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.button_address_ok = new global::Gtk.Button ();
		this.button_address_ok.CanFocus = true;
		this.button_address_ok.Name = "button_address_ok";
		this.button_address_ok.UseUnderline = true;
		this.button_address_ok.Label = global::Mono.Unix.Catalog.GetString ("OK");
		this.table2.Add (this.button_address_ok);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.button_address_ok]));
		w1.TopAttach = ((uint)(5));
		w1.BottomAttach = ((uint)(6));
		w1.LeftAttach = ((uint)(3));
		w1.RightAttach = ((uint)(4));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.checkbutton_loop = new global::Gtk.CheckButton ();
		this.checkbutton_loop.CanFocus = true;
		this.checkbutton_loop.Name = "checkbutton_loop";
		this.checkbutton_loop.Label = global::Mono.Unix.Catalog.GetString ("Loop");
		this.checkbutton_loop.DrawIndicator = true;
		this.checkbutton_loop.UseUnderline = true;
		this.table2.Add (this.checkbutton_loop);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton_loop]));
		w2.TopAttach = ((uint)(5));
		w2.BottomAttach = ((uint)(6));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entry_address = new global::Gtk.Entry ();
		this.entry_address.CanFocus = true;
		this.entry_address.Name = "entry_address";
		this.entry_address.IsEditable = true;
		this.entry_address.InvisibleChar = '•';
		this.entry_address.Xalign = 1F;
		this.table2.Add (this.entry_address);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry_address]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entry_mpd = new global::Gtk.Entry ();
		this.entry_mpd.CanFocus = true;
		this.entry_mpd.Name = "entry_mpd";
		this.entry_mpd.Text = global::Mono.Unix.Catalog.GetString ("localhost");
		this.entry_mpd.IsEditable = true;
		this.entry_mpd.InvisibleChar = '•';
		this.entry_mpd.Xalign = 1F;
		this.table2.Add (this.entry_mpd);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry_mpd]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entry_winamp_address = new global::Gtk.Entry ();
		this.entry_winamp_address.CanFocus = true;
		this.entry_winamp_address.Name = "entry_winamp_address";
		this.entry_winamp_address.Text = global::Mono.Unix.Catalog.GetString ("localhost");
		this.entry_winamp_address.IsEditable = true;
		this.entry_winamp_address.InvisibleChar = '•';
		this.entry_winamp_address.Xalign = 1F;
		this.table2.Add (this.entry_winamp_address);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry_winamp_address]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entry_winamp_pass = new global::Gtk.Entry ();
		this.entry_winamp_pass.CanFocus = true;
		this.entry_winamp_pass.Name = "entry_winamp_pass";
		this.entry_winamp_pass.Text = global::Mono.Unix.Catalog.GetString ("pass");
		this.entry_winamp_pass.IsEditable = true;
		this.entry_winamp_pass.InvisibleChar = '•';
		this.entry_winamp_pass.Xalign = 1F;
		this.table2.Add (this.entry_winamp_pass);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry_winamp_pass]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entry_winamp_port = new global::Gtk.Entry ();
		this.entry_winamp_port.WidthRequest = 80;
		this.entry_winamp_port.CanFocus = true;
		this.entry_winamp_port.Name = "entry_winamp_port";
		this.entry_winamp_port.Text = global::Mono.Unix.Catalog.GetString ("4800");
		this.entry_winamp_port.IsEditable = true;
		this.entry_winamp_port.MaxLength = 5;
		this.entry_winamp_port.InvisibleChar = '•';
		this.table2.Add (this.entry_winamp_port);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry_winamp_port]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(3));
		w7.RightAttach = ((uint)(4));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hscale_shift_speed = new global::Gtk.HScale (null);
		this.hscale_shift_speed.CanFocus = true;
		this.hscale_shift_speed.Name = "hscale_shift_speed";
		this.hscale_shift_speed.Adjustment.Upper = 100;
		this.hscale_shift_speed.Adjustment.PageIncrement = 1;
		this.hscale_shift_speed.Adjustment.StepIncrement = 1;
		this.hscale_shift_speed.DrawValue = true;
		this.hscale_shift_speed.Digits = 0;
		this.hscale_shift_speed.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.hscale_shift_speed);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.hscale_shift_speed]));
		w8.TopAttach = ((uint)(5));
		w8.BottomAttach = ((uint)(6));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label_address = new global::Gtk.Label ();
		this.label_address.Name = "label_address";
		this.label_address.LabelProp = global::Mono.Unix.Catalog.GetString ("Ledmatrix Adresse");
		this.table2.Add (this.label_address);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.label_address]));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Winamp Adresse");
		this.table2.Add (this.label2);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Winamp Pass");
		this.table2.Add (this.label3);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString (":");
		this.table2.Add (this.label4);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Mpd Adresse");
		this.table2.Add (this.label5);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
		w13.TopAttach = ((uint)(3));
		w13.BottomAttach = ((uint)(4));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table2);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Einstellungen</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 600;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview2 = new global::Gtk.TreeView ();
		this.treeview2.HeightRequest = 150;
		this.treeview2.CanFocus = true;
		this.treeview2.Name = "treeview2";
		this.treeview2.Reorderable = true;
		this.GtkScrolledWindow.Add (this.treeview2);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w18.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("%c\tCenter\t\t\t%h\tStunde\t\t%a\tArtist\n%g\tGrün\t\t\t%m\tMinute\t\t%t\tTitle\n%r\tRot\t\t\t\t%s\tSekunde\t\t%2%T Tree\n%o\tOrange\t\t\t\t\t\t\t%R\tRSS Feed\n%n\tZeilenumbruch\t%D\tTag\t\t\t%1\tSchrift mini\n%+\tEin Pixel tiefer\t%M\tMonat\t\t%8\tSchrift klein\n%-\tEin Pixel höher\t%Y\tJahr\t\t\t%2\tSchrift gross");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 737;
		this.DefaultHeight = 624;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.hscale_shift_speed.ValueChanged += new global::System.EventHandler (this.hscale_shift_speed_changed);
		this.entry_mpd.Activated += new global::System.EventHandler (this.on_entry_mpd_activated);
		this.entry_address.Activated += new global::System.EventHandler (this.on_entry_address_activated);
		this.checkbutton_loop.Clicked += new global::System.EventHandler (this.on_checkbutton_loop_clicked);
		this.button_address_ok.Clicked += new global::System.EventHandler (this.on_entry_address_activated);
	}
}
